name       : pydocstyle
version    : 6.1.1
release    : 6
source     :
    - https://github.com/PyCQA/pydocstyle/archive/6.1.1.tar.gz : 0ec238b731737da7c9ce3f7c135ee35b992b76a8bfa896007b90bf69a112927c
homepage   : http://pydocstyle.org/
license    : MIT
component  : programming.python
summary    : Docstring style checker
description: |
    pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
rundeps    :
    - python-snowballstemmer
build      : |
    %python3_setup
install    : |
    %python3_install
