name       : pydocstyle
version    : 4.0.1
release    : 2
source     :
    - https://github.com/PyCQA/pydocstyle/archive/4.0.1.tar.gz : 15cda50d4ede4a90e8ceb53c42234408d7e6b5e73914c5ccbb55556e7b28e914
homepage   : http://pydocstyle.org/
license    : MIT
component  : programming.python
summary    : Docstring style checker
description: |
    pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
rundeps    :
    - python-snowballstemmer
build      : |
    %python3_setup
install    : |
    %python3_install
